// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkVdcfhQ5lxiZHHenssyLgPmZp2TBbmU',
    appId: '1:685342198527:web:853188efa9fbd14b90daca',
    messagingSenderId: '685342198527',
    projectId: 'scholar-chat-app-869fb',
    authDomain: 'scholar-chat-app-869fb.firebaseapp.com',
    storageBucket: 'scholar-chat-app-869fb.appspot.com',
    measurementId: 'G-XKB8T62PSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHQN5E1j9-LH2147iaQ716Gtb4BJQ5yM',
    appId: '1:685342198527:android:88536ed23aa65ce290daca',
    messagingSenderId: '685342198527',
    projectId: 'scholar-chat-app-869fb',
    storageBucket: 'scholar-chat-app-869fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4I6dbwNl-rpGQZ8NYiekN6dC7pWKgg7s',
    appId: '1:685342198527:ios:3d68ed7b4ea81e6290daca',
    messagingSenderId: '685342198527',
    projectId: 'scholar-chat-app-869fb',
    storageBucket: 'scholar-chat-app-869fb.appspot.com',
    iosClientId: '685342198527-spdqpj77tkqveh86kbgf81j9241hs6gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.warehouseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4I6dbwNl-rpGQZ8NYiekN6dC7pWKgg7s',
    appId: '1:685342198527:ios:3d68ed7b4ea81e6290daca',
    messagingSenderId: '685342198527',
    projectId: 'scholar-chat-app-869fb',
    storageBucket: 'scholar-chat-app-869fb.appspot.com',
    iosClientId: '685342198527-spdqpj77tkqveh86kbgf81j9241hs6gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.warehouseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5GBl2_hoUEMj8Iq4fGbPed5WPVy19G5o',
    appId: '1:685342198527:web:d8c0c4e190eb4d2590daca',
    messagingSenderId: '685342198527',
    projectId: 'scholar-chat-app-869fb',
    authDomain: 'scholar-chat-app-869fb.firebaseapp.com',
    storageBucket: 'scholar-chat-app-869fb.appspot.com',
    measurementId: 'G-WZRBDGN0HM',
  );
}
